paths:
  data_econ_characteristics: "data/raw_data/data_econ_characteristics.csv"
  data_report_card: "data/raw_data/2025-Report-Card-Public-Data-Set.xlsx"
  schools: "data/raw_data/dir_ed_entities.xls"
  output_directory: "data/output/20260109/"



